# Generated by Django 5.2 on 2025-07-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscategory",
            name="client_nickname",
            field=models.CharField(
                default="Clients",
                help_text="Plural term for clients (Bars, Customers, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="client_nickname_singular",
            field=models.CharField(
                default="Client", help_text="Singular client term", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="location_nickname",
            field=models.CharField(
                default="Locations",
                help_text="Plural term for locations (Venues, Sites, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="location_nickname_singular",
            field=models.CharField(
                default="Location", help_text="Singular location term", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="material_nickname",
            field=models.CharField(
                default="Materials",
                help_text="Plural term for materials/inventory",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="material_nickname_singular",
            field=models.CharField(
                default="Material", help_text="Singular material term", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="material_type_nicknames",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Nicknames for material types (device, hardware, etc.)",
            ),
        ),
    ]
