# Generated by Django 5.2 on 2025-06-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_address_object_id'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-contract_signed_date', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='configurablechoice',
            name='choice_type',
            field=models.CharField(choices=[('location_type', 'Location Type'), ('location_status', 'Location Status'), ('access_requirement', 'Access Requirement'), ('work_hours', 'Work Hours'), ('document_type', 'Document Type'), ('note_type', 'Note Type'), ('priority_level', 'Priority Level'), ('project_status', 'Project Status'), ('task_type', 'Task Type'), ('custom', 'Custom Field Choice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom location data'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['business_category', 'status'], name='location_lo_busines_5f8b74_idx'),
        ),
    ]
