# Generated by Django 5.2 on 2025-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_businesscategory_client_nickname_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="delivery_restrictions",
            field=models.TextField(
                blank=True, help_text="Any delivery restrictions or scheduling notes"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="environmental_conditions",
            field=models.TextField(
                blank=True,
                help_text="Notable environmental conditions (temperature, humidity, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="storage_limitations",
            field=models.TextField(
                blank=True, help_text="Limitations on materials storage at the site"
            ),
        ),
    ]
