# Generated by Django 5.2 on 2025-06-07 20:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, help_text='Company name', max_length=200)),
                ('company_url', models.URLField(blank=True, help_text='Company website')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='uploads/client/logos/%Y/%m/%d/')),
                ('business_type', models.CharField(blank=True, choices=[('corporation', 'Corporation'), ('llc', 'LLC'), ('partnership', 'Partnership'), ('sole_prop', 'Sole Proprietorship'), ('non_profit', 'Non-Profit'), ('government', 'Government')], max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='EIN or Tax ID', max_length=20)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active Client'), ('inactive', 'Inactive'), ('former', 'Former Client')], default='prospect', max_length=20)),
                ('date_of_contact', models.DateField(blank=True, help_text='First contact date', null=True)),
                ('date_of_contract', models.DateField(blank=True, help_text='First contract date', null=True)),
                ('ytd_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Year to date revenue', max_digits=18, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total lifetime revenue', max_digits=18, null=True)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_on_receipt', 'Due on Receipt'), ('custom', 'Custom Terms')], default='net_30', max_length=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('summary', models.TextField(blank=True, help_text='Client description and notes', max_length=2000)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom client data')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['company_name'], name='client_clie_company_73ca72_idx'), models.Index(fields=['status'], name='client_clie_status_2ddb37_idx'), models.Index(fields=['date_of_contact'], name='client_clie_date_of_f1c356_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Q1 2025, FY 2025, etc.', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Period')], max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='client_fina_start_d_36c491_idx'), models.Index(fields=['is_current'], name='client_fina_is_curr_3d94d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField(db_index=True, help_text='Link to existing Project')),
                ('budgeted_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budgeted_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invoiced_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('collected_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('change_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id'], name='client_proj_project_ae7d48_idx'), models.Index(fields=['percent_complete'], name='client_proj_percent_0634e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('site', 'Site Address'), ('mailing', 'Mailing Address')], max_length=50)),
                ('attention_line', models.CharField(blank=True, help_text='Attn: John Doe', max_length=100)),
                ('line1', models.CharField(help_text='Street address', max_length=200)),
                ('line2', models.CharField(blank=True, help_text='Apt, Suite, etc.', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(help_text='State or Province', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP or Postal Code', max_length=20)),
                ('country', models.CharField(default='US', help_text='Country Code', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-is_primary', 'label'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='client_addr_content_3b275c_idx'), models.Index(fields=['postal_code'], name='client_addr_postal__d76c1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Contact'), ('billing', 'Billing Contact'), ('technical', 'Technical Contact'), ('emergency', 'Emergency Contact')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('object_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-is_primary', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='client_cont_content_4c00a8_idx'), models.Index(fields=['email'], name='client_cont_email_d63cf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('material_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labor_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('change_order_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('warranty_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='client.client')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'period'], name='client_reve_client__9bfd33_idx'), models.Index(fields=['period'], name='client_reve_period__0b83c0_idx')],
                'unique_together': {('client', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WIPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='WIP Report Name', max_length=200)),
                ('report_date', models.DateField(help_text='Report date')),
                ('total_backlog', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_wip', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projects_prospecting', models.IntegerField(default=0)),
                ('projects_quoted', models.IntegerField(default=0)),
                ('projects_installing', models.IntegerField(default=0)),
                ('projects_complete', models.IntegerField(default=0)),
                ('projects_invoiced', models.IntegerField(default=0)),
                ('projects_paid', models.IntegerField(default=0)),
                ('detailed_data', models.JSONField(blank=True, default=dict)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialperiod')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='client_wipr_report__7951cf_idx'), models.Index(fields=['period'], name='client_wipr_period__d2e0c2_idx')],
            },
        ),
    ]
