# Generated by Django 5.2 on 2025-06-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
