# Generated by Django 5.2 on 2025-06-27 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_contact_object_id_alter_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="department",
            field=models.CharField(
                blank=True, help_text="Department or team", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="mobile",
            field=models.CharField(
                blank=True,
                help_text="Mobile phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.",
                        regex="^\\+?[\\d\\s().-]{7,20}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the contact"
            ),
        ),
    ]
