# Generated by Django 5.2 on 2025-07-04 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_contact_department_contact_mobile_contact_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=200)),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_locations",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
