# Generated by Django 5.2 on 2025-06-20 04:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Work date")),
                ("start_time", models.TimeField(help_text="Start time")),
                ("end_time", models.TimeField(help_text="End time")),
                (
                    "lunch_start",
                    models.TimeField(
                        blank=True, help_text="Lunch break start", null=True
                    ),
                ),
                (
                    "lunch_end",
                    models.TimeField(
                        blank=True, help_text="Lunch break end", null=True
                    ),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Additional break time in minutes",
                        validators=[django.core.validators.MaxValueValidator(480)],
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Time"),
                            ("overtime", "Overtime"),
                            ("double_time", "Double Time"),
                            ("holiday", "Holiday"),
                            ("sick", "Sick Leave"),
                            ("vacation", "Vacation"),
                            ("personal", "Personal Time"),
                            ("training", "Training"),
                            ("travel", "Travel Time"),
                            ("on_call", "On Call"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Work location", max_length=200
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate for this timecard (overrides worker default)",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Miles driven for work",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Work-related expenses",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo from work site",
                        null=True,
                        upload_to="timecards/photos/%Y/%m/%d/",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project worked on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.project",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker who worked these hours",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeCardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attachment file",
                        upload_to="timecards/attachments/%Y/%m/%d/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the attachment",
                        max_length=200,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timecard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="timecard.timecard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Period name (e.g., "Week ending 12/01/2024")',
                        max_length=100,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom Period"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Period start date")),
                ("end_date", models.DateField(help_text="Period end date")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Timesheet submission deadline", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("start_date", "end_date", "period_type")},
            },
        ),
        migrations.AddField(
            model_name="timecard",
            name="timesheet_period",
            field=models.ForeignKey(
                blank=True,
                help_text="Payroll period this timecard belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="timecard.timesheetperiod",
            ),
        ),
        migrations.CreateModel(
            name="TimesheetSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "regular_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sick_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "vacation_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_mileage",
                    models.DecimalField(decimal_places=1, default=0, max_digits=8),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="timecard.timesheetperiod",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period__start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="timecard",
            index=models.Index(
                fields=["worker", "date"], name="timecard_ti_worker__795db9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timecard",
            index=models.Index(
                fields=["project", "date"], name="timecard_ti_project_e07cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timecard",
            index=models.Index(
                fields=["date", "status"], name="timecard_ti_date_952fe9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timecard",
            unique_together={("worker", "date", "start_time", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="timesheetsummary",
            unique_together={("worker", "period")},
        ),
    ]
