# Generated by Django 5.2 on 2025-07-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timecard", "0001_initial"),
        ("todo", "0002_task_prepared_for_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="timecard",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific task worked on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timecards",
                to="todo.task",
            ),
        ),
    ]
