# Generated by Django 5.2 on 2025-06-20 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department responsible for asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="company.department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_office",
            field=models.ForeignKey(
                blank=True,
                help_text="Office where asset is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="company.office",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_worker",
            field=models.ForeignKey(
                blank=True,
                help_text="Worker currently assigned this asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="company",
            field=models.ForeignKey(
                help_text="Company that owns this asset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="company.company",
            ),
        ),
    ]
