# Generated by Django 5.2 on 2025-06-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0002_initial'),
        ('company', '0001_initial'),
        ('location', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_project',
            field=models.ForeignKey(blank=True, help_text='Project currently using this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assets', to='project.project'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='asset.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.office'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='business_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='location.businesscategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetdepreciation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='asset.asset'),
        ),
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='asset.asset'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('business_category', 'name')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'status'], name='asset_asset_company_a6fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='asset_asset_categor_3e8d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assigned_worker'], name='asset_asset_assigne_c78ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['current_project'], name='asset_asset_current_6c50c1_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_maintenance_date'], name='asset_asset_next_ma_426432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together={('asset', 'depreciation_year')},
        ),
    ]
