# Generated by Django 5.2 on 2025-06-07 20:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the purchase type (e.g., Air Fair, Equipment, Meals)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the purchase type (e.g., AF, EQ, ML)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this purchase type covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this purchase type is currently available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Type',
                'verbose_name_plural': 'Purchase Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(help_text='Date of purchase (YYYY-MM-DD format)')),
                ('company_name', models.CharField(help_text='Name of the company/vendor where purchase was made', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the purchase', max_length=2000)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload an image of the receipt', null=True, upload_to='receipts/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about this receipt')),
                ('is_reimbursed', models.BooleanField(default=False, help_text='Whether this expense has been reimbursed')),
                ('reimbursement_date', models.DateField(blank=True, help_text='Date when reimbursement was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project this expense is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='project.project')),
                ('purchase_type', models.ForeignKey(help_text='Type of purchase made', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receipts.purchasetype')),
                ('worker', models.ForeignKey(help_text='Employee who made the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-date_of_purchase', '-created_at'],
                'indexes': [models.Index(fields=['date_of_purchase'], name='receipts_re_date_of_d8f433_idx'), models.Index(fields=['project'], name='receipts_re_project_0df9b9_idx'), models.Index(fields=['worker'], name='receipts_re_worker__252532_idx'), models.Index(fields=['purchase_type'], name='receipts_re_purchas_9bd02c_idx')],
            },
        ),
    ]
