# Generated by Django 5.2 on 2025-07-04 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_servicelocation"),
        ("project", "0005_project_locations_project_primary_location_and_more"),
        ("receipts", "0001_initial"),
        ("travel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="service_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Service location for this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="client.servicelocation",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Trip this expense is part of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="travel.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["service_location"], name="receipts_re_service_7a0e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["trip"], name="receipts_re_trip_id_b0da08_idx"),
        ),
    ]
