# Generated by Django 5.2 on 2025-07-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_add_trip_location_fields"),
    ]

    def set_nulls(apps, schema_editor):
        Receipt = apps.get_model("receipts", "Receipt")
        Receipt.objects.filter(service_location__isnull=True).update(service_location=None)
        Receipt.objects.filter(trip__isnull=True).update(trip=None)

    operations = [
        migrations.RunPython(set_nulls, migrations.RunPython.noop),
    ]
