# Generated by Django 5.2 on 2025-06-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["first_name", "last_name"],
                "permissions": [
                    ("view_compensation", "Can view compensation information")
                ],
            },
        ),
    ]
