# Generated by Django 5.2 on 2025-06-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_department_company_alter_office_company'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='company.company'),
        ),
    ]
