# Generated by Django 5.2 on 2025-07-04 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="prepared_for_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Worker who prepared this task for others",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_prepared_for",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
