# Generated by Django 5.2 on 2025-06-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related tasks",
                related_name="events",
                to="todo.task",
            ),
        ),
    ]
