# Generated by Django 5.2 on 2025-07-04 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("material", "0002_materiallifecycle"),
        ("project", "0005_project_locations_project_primary_location_and_more"),
        ("schedule", "0002_event_tasks"),
        ("todo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="related_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked object type (Trip or Receipt)",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "travel"), ("model", "trip")),
                    models.Q(("app_label", "receipts"), ("model", "receipt")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_object_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="ID of the linked object", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["related_content_type", "related_object_id"],
                name="schedule_ev_related_3a9c55_idx",
            ),
        ),
    ]
