# Generated by Django 5.2 on 2025-07-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("material", "0001_initial"),
        ("project", "0005_project_locations_project_primary_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("stored_at", models.DateTimeField(blank=True, null=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("fabricated_at", models.DateTimeField(blank=True, null=True)),
                ("assembled_at", models.DateTimeField(blank=True, null=True)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("repaired_at", models.DateTimeField(blank=True, null=True)),
                ("refurbished_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("billed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("warranted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prepared_for_object_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_for_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "project_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="project.projectmaterial",
                    ),
                ),
                (
                    "purchased_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="material.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project_material", "purchased_from"],
                        name="material_ma_project_830a31_idx",
                    )
                ],
            },
        ),
    ]
