# Generated by Django 5.2 on 2025-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("industry_details", models.TextField(blank=True)),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Company"),
                            ("collaborative", "Collaborative"),
                            ("ecosystem", "Ecosystem"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("project", "Per Project"),
                            ("product", "Per Product"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                ("enables_shared_inventory", models.BooleanField(default=False)),
                ("enables_shared_workforce", models.BooleanField(default=False)),
                ("enables_shared_clients", models.BooleanField(default=False)),
                ("enables_cross_selling", models.BooleanField(default=False)),
                ("workflow_requirements", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
