# Generated by Django 5.2 on 2025-07-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_alter_businessconfiguration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminologyAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_label", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("field", models.CharField(max_length=50)),
                ("alias", models.CharField(max_length=100)),
                (
                    "business_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminology_aliases",
                        to="business.businessconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["app_label", "model", "field"],
                "unique_together": {("business_config", "app_label", "model", "field")},
            },
        ),
    ]
