# Generated by Django 5.2 on 2025-06-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('project', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdevice',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='todo.task'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project.project'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='business_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='location.businesscategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projecttemplate'),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Other scope items this depends on', to='project.scopeofwork'),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='project',
            field=models.ForeignKey(help_text='Project this scope belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='project.project'),
        ),
        migrations.AddField(
            model_name='projectdevice',
            name='scope_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.scopeofwork'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttemplate',
            unique_together={('business_category', 'name')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['location', 'status'], name='project_pro_locatio_db2d98_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'due_date'], name='project_pro_status_1b437a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_manager', 'status'], name='project_pro_project_0613a3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['job_number'], name='project_pro_job_num_b19538_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'due_date'], name='project_pro_start_d_b35ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['project', 'priority'], name='project_sco_project_16ab6e_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeofwork',
            index=models.Index(fields=['percent_complete'], name='project_sco_percent_301126_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdevice',
            index=models.Index(fields=['project', 'status'], name='project_pro_project_270fda_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdevice',
            index=models.Index(fields=['delivered_date'], name='project_pro_deliver_8444a1_idx'),
        ),
    ]
