# Generated by Django 5.2 on 2025-06-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("tracks_inventory", models.BooleanField(default=False)),
                ("requires_scheduling", models.BooleanField(default=False)),
                ("billable", models.BooleanField(default=False)),
                ("workflow_stage", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_categories",
                        to="location.businesscategory",
                    ),
                ),
            ],
            options={
                "ordering": ["business_category", "sort_order", "name"],
                "unique_together": {("business_category", "name")},
            },
        ),
    ]
