# Generated by Django 5.2 on 2025-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_servicelocation"),
        ("project", "0003_create_project_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="project_pro_locatio_db2d98_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="location",
        ),
        migrations.AddField(
            model_name="project",
            name="service_locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations serviced by this project",
                related_name="projects",
                to="client.servicelocation",
            ),
        ),
    ]
