# Generated by Django 5.2 on 2025-07-04 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_add_location_logistics_fields"),
        ("project", "0004_remove_project_project_pro_locatio_db2d98_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="All locations associated with this project",
                related_name="projects",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="primary_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary location for this project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_projects",
                to="location.location",
            ),
        ),
        migrations.AddField(
            model_name="projectmaterial",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location this material is destined for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_materials",
                to="location.location",
            ),
        ),
    ]
