# Generated by Django 5.2 on 2025-06-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company'),
        ),
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this office belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='company.company'),
        ),
    ]
