# Generated by Django 5.2 on 2025-06-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Deployment business configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.businessconfiguration",
            ),
        ),
    ]
