# Generated by Django 5.2 on 2025-06-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_business_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="collaboration_permissions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Permissions for cross-company collaboration",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_company",
            field=models.BooleanField(
                default=False, help_text="Main company in a collaborative deployment"
            ),
        ),
        migrations.CreateModel(
            name="CompanyPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Strategic"),
                            ("supplier", "Supplier"),
                            ("subcontractor", "Subcontractor"),
                            ("affiliate", "Affiliate"),
                        ],
                        default="strategic",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_initiated",
                        to="company.company",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_received",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ["from_company", "to_company"],
                "unique_together": {("from_company", "to_company")},
            },
        ),
        migrations.AddField(
            model_name="company",
            name="partner_companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partner companies in collaborative deployments",
                related_name="partners",
                through="company.CompanyPartnership",
                to="company.company",
            ),
        ),
    ]
