# Generated by Django 5.2 on 2025-07-04 04:34

from django.db import migrations, models
from django.conf import settings
from django.apps import apps as django_apps


def create_business_apps(apps, schema_editor):
    BusinessApplication = apps.get_model("company", "BusinessApplication")
    for config in django_apps.get_app_configs():
        BusinessApplication.objects.get_or_create(
            label=config.name,
            defaults={"name": getattr(config, "verbose_name", config.label)},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_company_collaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Django app label", max_length=100, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Human readable name", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Application",
                "verbose_name_plural": "Business Applications",
                "ordering": ["label"],
            },
        ),
        migrations.RunPython(create_business_apps, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="company",
            name="business_apps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Installed applications enabled for this company",
                related_name="companies",
                to="company.businessapplication",
            ),
        ),
    ]
