# Generated by Django 5.2 on 2025-06-16

import uuid
import django.db.models.deletion
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WIPItem",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wip_items",
                        to="hr.worker",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wip_items",
                        to="project.project",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        max_length=20,
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("complete", "Complete"),
                        ],
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
                ),
                ("estimated_completion", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="wipitem",
            index=models.Index(fields=["project", "status"], name="wipitem_proj_status_idx"),
        ),
        migrations.AddIndex(
            model_name="wipitem",
            index=models.Index(fields=["assigned_to"], name="wipitem_assigned_idx"),
        ),
    ]

